"use client";

import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";

export default function ApprovalsPage() {
  const [requests, setRequests] = useState<any[]>([]);
  const [activeTab, setActiveTab] = useState("PENDING");
  const [selectedRequest, setSelectedRequest] = useState<any>(null);
  const [notes, setNotes] = useState("");
  const [loading, setLoading] = useState(false);
  const [actionLoading, setActionLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetchApprovals();
  }, [activeTab]);

  const fetchApprovals = async () => {
    setLoading(true);
    setError(null);
    setSelectedRequest(null);
    const token = localStorage.getItem("safeops_token");
    if (!token) return;

    try {
      const response = await fetch(`http://localhost:8000/api/v1/approvals/?status_filter=${activeTab}`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      if (response.status === 401) {
        handleUnauthorized();
        return;
      }

      if (!response.ok) {
        throw new Error("Failed to load approvals queue");
      }

      const data = await response.json();
      if (Array.isArray(data)) {
        setRequests(data);
      }
    } catch (err: any) {
      setError(err.message || "Could not retrieve approvals queue");
    } finally {
      setLoading(false);
    }
  };

  const handleUnauthorized = () => {
    localStorage.removeItem("safeops_token");
    window.location.reload();
  };

  const handleDecision = async (id: string, decision: "APPROVED" | "REJECTED") => {
    setActionLoading(true);
    setError(null);
    const token = localStorage.getItem("safeops_token");
    if (!token) return;

    try {
      const response = await fetch(`http://localhost:8000/api/v1/approvals/${id}/decide`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          decision,
          reason: notes,
        }),
      });

      if (response.status === 401) {
        handleUnauthorized();
        return;
      }

      if (!response.ok) {
        const data = await response.json().catch(() => ({}));
        throw new Error(data.detail || `Failed to register ${decision.toLowerCase()} action`);
      }

      // Reload list
      await fetchApprovals();
      setSelectedRequest(null);
      setNotes("");
    } catch (err: any) {
      setError(err.message || "Error submitting decision");
    } finally {
      setActionLoading(false);
    }
  };

  const filteredRequests = requests;

  return (
    <div className="flex flex-col gap-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-slate-800">Action Approvals Queue</h2>
          <p className="text-slate-500 text-xs mt-1">Review, authorize, or reject operations request tickets generated by active AI agents.</p>
        </div>
        
        {/* Tab triggers */}
        <div className="bg-slate-100 border border-slate-200 rounded-xl p-1 flex gap-1 font-mono text-xs">
          {["PENDING", "APPROVED", "REJECTED"].map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-3 py-1.5 rounded-lg font-semibold transition ${
                activeTab === tab 
                  ? "bg-white text-slate-900 border border-slate-200/50 shadow-sm" 
                  : "text-slate-500 hover:text-slate-900"
              }`}
            >
              {tab}
            </button>
          ))}
        </div>
      </div>

      {error && (
        <div className="p-3.5 bg-rose-50 border border-rose-200 text-rose-700 text-xs rounded-xl font-medium">
          {error}
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
        {/* List of Requests */}
        <div className="lg:col-span-2 flex flex-col gap-4">
          {loading ? (
            <div className="bg-white border border-slate-200 rounded-2xl p-8 text-center text-slate-400 text-xs">
              Loading requests queue...
            </div>
          ) : filteredRequests.length === 0 ? (
            <div className="bg-white border border-slate-200 rounded-2xl p-8 text-center text-slate-400 text-xs">
              No execution requests found matching tab status.
            </div>
          ) : (
            <AnimatePresence mode="popLayout">
              {filteredRequests.map((req) => (
                <motion.div
                  key={req.id}
                  layoutId={req.id}
                  onClick={() => setSelectedRequest(req)}
                  className={`bg-white border rounded-2xl p-5 cursor-pointer transition shadow-sm hover:shadow-md ${
                    selectedRequest?.id === req.id 
                      ? "border-indigo-600 ring-1 ring-indigo-600/30" 
                      : "border-slate-200 hover:border-slate-300"
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <code className="text-indigo-600 text-xs font-mono font-bold bg-indigo-50 px-2.5 py-1 rounded border border-indigo-100/50">
                        {req.tool_name}()
                      </code>
                      <span className="text-slate-400 text-[10px] font-mono">ID: {req.id}</span>
                    </div>
                    <span className={`px-2 py-0.5 rounded text-[10px] font-mono font-bold ${
                      req.risk_score < 3.0 ? "bg-emerald-50 text-emerald-700 border border-emerald-100" :
                      req.risk_score < 7.0 ? "bg-amber-50 text-amber-700 border border-amber-100" :
                      "bg-rose-50 text-rose-700 border border-rose-100"
                    }`}>
                      Risk: {req.risk_score.toFixed(1)}
                    </span>
                  </div>
                  
                  <div className="mt-4 flex flex-col gap-1.5 text-xs text-slate-700">
                    <div>
                      <span className="text-slate-400 font-mono text-[10px] uppercase font-bold mr-1">Timestamp:</span>
                      {new Date(req.created_at).toLocaleString()}
                    </div>
                    <div className="truncate">
                      <span className="text-slate-400 font-mono text-[10px] uppercase font-bold mr-1">Args:</span>
                      <code className="font-mono text-slate-600 bg-slate-50 px-1 py-0.5 rounded border border-slate-100">
                        {JSON.stringify(req.arguments)}
                      </code>
                    </div>
                  </div>
                </motion.div>
              ))}
            </AnimatePresence>
          )}
        </div>

        {/* Action Panel Detail view */}
        <div className="lg:col-span-1">
          {selectedRequest ? (
            <div className="bg-white border border-slate-200 rounded-2xl p-6 flex flex-col gap-6 shadow-sm sticky top-6">
              <div>
                <span className="text-[10px] font-mono text-slate-400 font-bold uppercase tracking-widest block">TICKET INSPECTION</span>
                <h3 className="text-base font-bold text-slate-800 mt-1">Review Request</h3>
              </div>

              <div className="flex flex-col gap-4 text-xs font-mono divide-y divide-slate-100">
                <div className="py-2.5">
                  <span className="text-slate-400 block mb-1 font-bold text-[10px]">TOOL FUNCTION:</span>
                  <span className="text-indigo-600 font-bold text-sm">{selectedRequest.tool_name}()</span>
                </div>
                <div className="py-2.5">
                  <span className="text-slate-400 block mb-1 font-bold text-[10px]">ARGUMENTS (JSON):</span>
                  <pre className="bg-slate-50 p-3 rounded-xl border border-slate-200 text-slate-700 overflow-x-auto text-[10px] font-mono leading-relaxed">
                    {JSON.stringify(selectedRequest.arguments, null, 2)}
                  </pre>
                </div>
                <div className="py-2.5">
                  <span className="text-slate-400 block mb-1 font-bold text-[10px]">RISK EXPLANATION:</span>
                  <p className="text-slate-600 font-sans leading-relaxed text-xs">{selectedRequest.risk_explanation || "No explanation provided."}</p>
                </div>
                <div className="py-2.5">
                  <span className="text-slate-400 block mb-1 font-bold text-[10px]">ENVIRONMENT:</span>
                  <span className="text-slate-700 uppercase font-bold">{selectedRequest.environment}</span>
                </div>
                {selectedRequest.reason && (
                  <div className="py-2.5">
                    <span className="text-slate-400 block mb-1 font-bold text-[10px]">DECISION REASON:</span>
                    <p className="text-slate-600 font-sans leading-relaxed text-xs">{selectedRequest.reason}</p>
                  </div>
                )}
              </div>

              {selectedRequest.status === "PENDING" && (
                <div className="flex flex-col gap-3">
                  <textarea
                    placeholder="Approval comments or rejection justification notes..."
                    value={notes}
                    onChange={(e) => setNotes(e.target.value)}
                    className="w-full bg-slate-50 border border-slate-200 hover:border-slate-300 rounded-xl p-3 text-xs text-slate-900 focus:outline-none focus:border-indigo-600 focus:bg-white transition h-20 resize-none"
                  />
                  <div className="grid grid-cols-2 gap-3">
                    <button
                      onClick={() => handleDecision(selectedRequest.id, "REJECTED")}
                      disabled={actionLoading}
                      className="py-2.5 bg-rose-50 hover:bg-rose-100 text-rose-700 border border-rose-200 rounded-xl text-xs font-bold transition disabled:opacity-50"
                    >
                      Reject Request
                    </button>
                    <button
                      onClick={() => handleDecision(selectedRequest.id, "APPROVED")}
                      disabled={actionLoading}
                      className="py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-bold transition shadow-sm hover:shadow disabled:opacity-50"
                    >
                      Authorize Action
                    </button>
                  </div>
                </div>
              )}
            </div>
          ) : (
            <div className="bg-white border border-slate-200 rounded-2xl p-6 text-center text-slate-400 text-xs font-mono shadow-sm">
              Select a request ticket to inspect details and sign off.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
