"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

// Mock approvals queue reflecting the active database requests
const INITIAL_REQUESTS = [
  {
    id: "ap_89d1a1b8",
    tool: "restart_service",
    arguments: { service_name: "postgresql", provider: "systemd" },
    environment: "production",
    risk: 5.5,
    rationale: "Restarting PostgreSQL on production systems can terminate active client sessions and cause 5-10s of application downtime.",
    client: "Windsurf developer",
    status: "PENDING"
  },
  {
    id: "ap_90a3a4b1",
    tool: "update_package",
    arguments: { package_name: "neovim", target_dir: "~/.config/nvim" },
    environment: "production",
    risk: 4.8,
    rationale: "Updating neovim on the system. Rollback snapshot of ~/.config/nvim is scheduled before modification.",
    client: "Claude Code",
    status: "APPROVED"
  }
];

export default function ApprovalsPage() {
  const [requests, setRequests] = useState(INITIAL_REQUESTS);
  const [activeTab, setActiveTab] = useState("PENDING");
  const [selectedRequest, setSelectedRequest] = useState<any>(null);
  const [notes, setNotes] = useState("");

  const handleDecision = (id: string, decision: "APPROVED" | "REJECTED") => {
    setRequests(
      requests.map((r) => (r.id === id ? { ...r, status: decision } : r))
    );
    setSelectedRequest(null);
    setNotes("");
  };

  const filteredRequests = requests.filter((r) => r.status === activeTab);

  return (
    <div className="flex flex-col gap-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-white">Action Approvals Queue</h2>
          <p className="text-zinc-400 text-sm mt-1">Review, authorize, or reject operations request tickets generated by active AI agents.</p>
        </div>
        
        {/* Tab triggers */}
        <div className="bg-[#18181b] border border-cyber-border rounded-lg p-1 flex gap-1 font-mono text-xs">
          <button
            onClick={() => setActiveTab("PENDING")}
            className={`px-3 py-1.5 rounded-md font-semibold transition ${
              activeTab === "PENDING" ? "bg-zinc-800 text-white border border-cyber-border" : "text-zinc-400 hover:text-white"
            }`}
          >
            PENDING ({requests.filter(r => r.status === "PENDING").length})
          </button>
          <button
            onClick={() => setActiveTab("APPROVED")}
            className={`px-3 py-1.5 rounded-md font-semibold transition ${
              activeTab === "APPROVED" ? "bg-zinc-800 text-white border border-cyber-border" : "text-zinc-400 hover:text-white"
            }`}
          >
            APPROVED ({requests.filter(r => r.status === "APPROVED").length})
          </button>
          <button
            onClick={() => setActiveTab("REJECTED")}
            className={`px-3 py-1.5 rounded-md font-semibold transition ${
              activeTab === "REJECTED" ? "bg-zinc-800 text-white border border-cyber-border" : "text-zinc-400 hover:text-white"
            }`}
          >
            REJECTED ({requests.filter(r => r.status === "REJECTED").length})
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
        {/* List of Requests */}
        <div className="lg:col-span-2 flex flex-col gap-4">
          <AnimatePresence mode="popLayout">
            {filteredRequests.length === 0 ? (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="bg-cyber-card border border-cyber-border rounded-xl p-8 text-center text-zinc-500 text-sm"
              >
                No execution requests found matching tab status.
              </motion.div>
            ) : (
              filteredRequests.map((req) => (
                <motion.div
                  key={req.id}
                  layoutId={req.id}
                  onClick={() => setSelectedRequest(req)}
                  className={`bg-cyber-card border rounded-xl p-5 cursor-pointer transition glow-card ${
                    selectedRequest?.id === req.id ? "border-cyber-cyan bg-zinc-900/20" : "border-cyber-border hover:bg-[#18181b]/10"
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <code className="text-cyber-cyan text-xs font-mono font-bold bg-cyber-cyan/5 px-2 py-1 rounded border border-cyber-cyan/15">
                        {req.tool}()
                      </code>
                      <span className="text-zinc-400 text-xs font-mono">ID: {req.id}</span>
                    </div>
                    <span className={`px-2 py-0.5 rounded text-xs font-mono font-bold ${
                      req.risk < 3.0 ? "bg-cyber-emerald/10 text-cyber-emerald border border-cyber-emerald/20" :
                      req.risk < 7.0 ? "bg-cyber-amber/10 text-cyber-amber border border-cyber-amber/20" :
                      "bg-cyber-rose/10 text-cyber-rose border border-cyber-rose/20"
                    }`}>
                      Risk: {req.risk.toFixed(1)}
                    </span>
                  </div>
                  
                  <div className="mt-4 flex flex-col gap-1 text-sm">
                    <div className="text-zinc-200">
                      <span className="text-zinc-500 font-mono text-xs">Agent:</span> {req.client}
                    </div>
                    <div className="text-zinc-400 text-xs mt-1 truncate">
                      <span className="text-zinc-500 font-mono">Args:</span> {JSON.stringify(req.arguments)}
                    </div>
                  </div>
                </motion.div>
              ))
            )}
          </AnimatePresence>
        </div>

        {/* Action Panel Detail view */}
        <div className="lg:col-span-1">
          {selectedRequest ? (
            <div className="bg-cyber-card border border-cyber-border rounded-xl p-6 flex flex-col gap-6 sticky top-6">
              <div>
                <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-widest block">TICKET INSPECTION</span>
                <h3 className="text-lg font-bold text-white mt-1">Review Request</h3>
              </div>

              <div className="flex flex-col gap-4 text-xs font-mono divide-y divide-cyber-border">
                <div className="py-2.5">
                  <span className="text-zinc-500 block mb-1">TOOL FUNCTION:</span>
                  <span className="text-cyber-cyan font-bold text-sm">{selectedRequest.tool}()</span>
                </div>
                <div className="py-2.5">
                  <span className="text-zinc-500 block mb-1">ARGUMENTS (JSON):</span>
                  <pre className="bg-[#0b0b0d] p-3 rounded border border-cyber-border text-zinc-300 overflow-x-auto">
                    {JSON.stringify(selectedRequest.arguments, null, 2)}
                  </pre>
                </div>
                <div className="py-2.5">
                  <span className="text-zinc-500 block mb-1">RISK EXPLANATION:</span>
                  <p className="text-zinc-400 font-sans leading-relaxed text-xs">{selectedRequest.rationale}</p>
                </div>
                <div className="py-2.5">
                  <span className="text-zinc-500 block mb-1">ENVIRONMENT:</span>
                  <span className="text-zinc-200 uppercase">{selectedRequest.environment}</span>
                </div>
              </div>

              {selectedRequest.status === "PENDING" && (
                <div className="flex flex-col gap-3">
                  <textarea
                    placeholder="Approval comments or rejection justification notes..."
                    value={notes}
                    onChange={(e) => setNotes(e.target.value)}
                    className="bg-[#0b0b0d] border border-cyber-border rounded-lg p-3 text-xs text-white focus:outline-none focus:border-cyber-cyan h-20 resize-none"
                  />
                  <div className="grid grid-cols-2 gap-3">
                    <button
                      onClick={() => handleDecision(selectedRequest.id, "REJECTED")}
                      className="py-2 bg-cyber-rose/10 hover:bg-cyber-rose/20 text-cyber-rose border border-cyber-rose/30 rounded-lg text-xs font-bold transition"
                    >
                      Reject Request
                    </button>
                    <button
                      onClick={() => handleDecision(selectedRequest.id, "APPROVED")}
                      className="py-2 bg-cyber-emerald hover:bg-cyber-emerald/90 text-white rounded-lg text-xs font-bold transition shadow-successGlow"
                    >
                      Authorize Action
                    </button>
                  </div>
                </div>
              )}
            </div>
          ) : (
            <div className="bg-cyber-card border border-cyber-border rounded-xl p-6 text-center text-zinc-500 text-xs font-mono">
              Select a request ticket to inspect details and sign off.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
