import hashlib
import json
from sqlalchemy.orm import Session
from ..models import AuditLog

class AuditLedger:
    @classmethod
    def generate_row_hash(
        cls, 
        previous_hash: str, 
        timestamp_str: str, 
        user_id: str, 
        client_id: str, 
        tool_name: str, 
        args_hash: str, 
        risk_score: float, 
        status: str
    ) -> str:
        """
        Generates the SHA256 chain hash for the audit record.
        """
        payload = f"{previous_hash}|{timestamp_str}|{user_id}|{client_id}|{tool_name}|{args_hash}|{risk_score}|{status}"
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()

    @classmethod
    def write_log(
        cls, 
        db: Session, 
        client_id: str, 
        tool_name: str, 
        arguments: dict, 
        risk_score: float, 
        status: str, 
        user_id: str = None, 
        approved_by: str = None
    ) -> AuditLog:
        """
        Calculates and appends a new audit record to the ledger chain.
        """
        # Fetch the most recent log to get the chain link hash
        last_log = db.query(AuditLog).order_by(AuditLog.timestamp.desc(), AuditLog.id.desc()).first()
        previous_hash = last_log.row_hash if last_log else "0" * 64

        # Compute arguments hash
        args_str = json.dumps(arguments or {}, sort_keys=True)
        args_hash = hashlib.sha256(args_str.encode("utf-8")).hexdigest()

        log_record = AuditLog(
            user_id=user_id,
            client_id=client_id,
            tool_name=tool_name,
            arguments_hash=args_hash,
            risk_score=risk_score,
            approved_by=approved_by,
            status=status,
            previous_hash=previous_hash,
            row_hash="TEMP"
        )
        
        db.add(log_record)
        db.flush() # Populate autogenerated fields (id, timestamp)
        
        # Calculate final chain link row hash
        row_hash = cls.generate_row_hash(
            previous_hash=previous_hash,
            timestamp_str=log_record.timestamp.isoformat(),
            user_id=str(log_record.user_id) if log_record.user_id else "",
            client_id=str(log_record.client_id),
            tool_name=log_record.tool_name,
            args_hash=args_hash,
            risk_score=log_record.risk_score or 0.0,
            status=log_record.status
        )
        
        log_record.row_hash = row_hash
        db.commit()
        return log_record
